"""
app/domain/planning.py
======================
Models representing the high-level research plan generated by the Planner.
"""

from datetime import datetime

from pydantic import BaseModel, Field

from app.domain.enums import ResearchDepth, TaskStatus
from app.domain.task import ResearchTask
from app.utils.ids import new_plan_id
from app.utils.time import utcnow


class ResearchPlan(BaseModel):
    """The master research plan containing multiple research sub-tasks."""

    plan_id: str = Field(
        default_factory=new_plan_id,
        description="Unique identifier for this plan.",
    )
    run_id: str = Field(..., description="ID of the research run this plan was built for.")
    original_query: str = Field(..., description="The original user query.")
    tasks: list[ResearchTask] = Field(
        default_factory=list,
        description="Decomposed sub-tasks for research execution.",
    )
    estimated_depth: ResearchDepth = Field(
        default=ResearchDepth.STANDARD,
        description="The planned depth setting of this execution.",
    )
    rationale: str = Field(
        default="",
        description="The Planner's overall strategic rationale for this decomposition.",
    )
    created_at: datetime = Field(default_factory=utcnow)

    @property
    def total_tasks(self) -> int:
        """Total number of tasks defined in this plan."""
        return len(self.tasks)

    @property
    def completed_tasks(self) -> int:
        """Total number of tasks that have finished executing."""
        return sum(1 for t in self.tasks if t.status == TaskStatus.COMPLETE)

    @property
    def progress(self) -> float:
        """Percentage of plan execution completion (from 0.0 to 1.0)."""
        if not self.tasks:
            return 0.0
        return self.completed_tasks / self.total_tasks
