"""
app/domain/report.py
===================
Models representing sections and the complete final synthesized Research Report.
"""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from app.domain.enums import ConfidenceLevel, OutputFormat
from app.domain.citation import Citation
from app.domain.critique import Contradiction, ResearchGap
from app.domain.metrics import TokenUsage
from app.utils.ids import new_report_id
from app.utils.time import utcnow


class ReportSection(BaseModel):
    """A subsection of the final synthesized research report."""

    title: str = Field(..., description="The title of this section.")
    content: str = Field(..., description="The section content formatted in markdown.")
    supporting_finding_ids: list[str] = Field(
        default_factory=list,
        description="IDs of consolidated facts/raw findings supporting this section.",
    )


class FinalReport(BaseModel):
    """The master Research Report generated by the Writer."""

    report_id: str = Field(
        default_factory=new_report_id,
        description="Unique identifier for this report.",
    )
    run_id: str = Field(..., description="The execution run this report was synthesized for.")
    query: str = Field(..., description="The original query investigated.")
    executive_summary: str = Field(..., description="High-level summary of findings and conclusions.")
    sections: list[ReportSection] = Field(default_factory=list, description="Detailed sections of the report.")
    citations: list[Citation] = Field(default_factory=list, description="Citations and bibliography index.")

    overall_confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    confidence_level: ConfidenceLevel = Field(default=ConfidenceLevel.MEDIUM)

    gaps_acknowledged: list[ResearchGap] = Field(
        default_factory=list,
        description="Outstanding research gaps that remain unfilled.",
    )
    contradictions_noted: list[Contradiction] = Field(
        default_factory=list,
        description="Noted conflicts that were investigated and synthesized.",
    )

    total_sources: int = Field(default=0, ge=0)
    total_findings: int = Field(default=0, ge=0)
    critic_passes: int = Field(default=0, ge=0)
    token_usage: TokenUsage = Field(default_factory=TokenUsage)
    output_format: OutputFormat = Field(default=OutputFormat.MARKDOWN)

    created_at: datetime = Field(default_factory=utcnow)
    elapsed_seconds: float = Field(default=0.0, ge=0.0)

    def model_post_init(self, __context: Any) -> None:
        """Derive confidence level tier from overall_confidence score after initialization."""
        score = self.overall_confidence
        if score < 0.2:
            self.confidence_level = ConfidenceLevel.VERY_LOW
        elif score < 0.4:
            self.confidence_level = ConfidenceLevel.LOW
        elif score < 0.6:
            self.confidence_level = ConfidenceLevel.MEDIUM
        elif score < 0.8:
            self.confidence_level = ConfidenceLevel.HIGH
        else:
            self.confidence_level = ConfidenceLevel.VERY_HIGH
