"""
research_agent.core
===================
Public re-exports for the core domain layer.
Import everything you need from here rather than from individual modules.
"""

from research_agent.core.contracts import (
    ErrorResponse,
    HealthResponse,
    ReportListItem,
    ReportListResponse,
    RunListItem,
    RunListResponse,
    RunStatusResponse,
    StartResearchRequest,
    StartResearchResponse,
    StreamEvent,
)
from research_agent.core.exceptions import (
    BudgetExhaustedError,
    CancellationError,
    DocumentReadError,
    ExtractionError,
    InvalidQueryError,
    LLMContextLimitError,
    LLMError,
    LLMOutputParseError,
    LLMRateLimitError,
    PlanningError,
    ResearchAgentError,
    ResearchError,
    RunNotFoundError,
    SearchError,
    StorageError,
    SynthesisError,
    TimeoutError,
    ToolError,
)
from research_agent.core.models import (
    Citation,
    ConfidenceLevel,
    Contradiction,
    Critique,
    FinalReport,
    Finding,
    OutputFormat,
    ReportSection,
    ResearchDepth,
    ResearchGap,
    ResearchPlan,
    ResearchRequest,
    ResearchStatus,
    ResearchTask,
    Source,
    SourceType,
    TaskStatus,
    TokenUsage,
)
from research_agent.core.state import (
    ProgressEvent,
    ResearchState,
    RunMetadata,
    create_initial_state,
    emit_event,
    get_all_findings,
    get_latest_critique,
    get_pending_tasks,
    is_budget_exhausted,
    should_stop_critic_loop,
)

__all__ = [
    # Contracts
    "ErrorResponse",
    "HealthResponse",
    "ReportListItem",
    "ReportListResponse",
    "RunListItem",
    "RunListResponse",
    "RunStatusResponse",
    "StartResearchRequest",
    "StartResearchResponse",
    "StreamEvent",
    # Exceptions
    "BudgetExhaustedError",
    "CancellationError",
    "DocumentReadError",
    "ExtractionError",
    "InvalidQueryError",
    "LLMContextLimitError",
    "LLMError",
    "LLMOutputParseError",
    "LLMRateLimitError",
    "PlanningError",
    "ResearchAgentError",
    "ResearchError",
    "RunNotFoundError",
    "SearchError",
    "StorageError",
    "SynthesisError",
    "TimeoutError",
    "ToolError",
    # Models
    "Citation",
    "ConfidenceLevel",
    "Contradiction",
    "Critique",
    "FinalReport",
    "Finding",
    "OutputFormat",
    "ReportSection",
    "ResearchDepth",
    "ResearchGap",
    "ResearchPlan",
    "ResearchRequest",
    "ResearchStatus",
    "ResearchTask",
    "Source",
    "SourceType",
    "TaskStatus",
    "TokenUsage",
    # State
    "ProgressEvent",
    "ResearchState",
    "RunMetadata",
    "create_initial_state",
    "emit_event",
    "get_all_findings",
    "get_latest_critique",
    "get_pending_tasks",
    "is_budget_exhausted",
    "should_stop_critic_loop",
]
