"""
Phase 3 — Domain Models
=======================
Pydantic v2 models that represent every entity in the research pipeline.
These are the canonical data shapes that flow between all agent nodes.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, HttpUrl, field_validator


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class ResearchDepth(str, Enum):
    """Controls how thorough the research run will be."""

    QUICK = "quick"        # 3–5 sources, 1 critic pass
    STANDARD = "standard"  # 8–12 sources, 2 critic passes
    DEEP = "deep"          # 15–25 sources, 3 critic passes


class ResearchStatus(str, Enum):
    """Lifecycle status of a research run."""

    QUEUED = "queued"
    PLANNING = "planning"
    RESEARCHING = "researching"
    CRITIQUING = "critiquing"
    SYNTHESIZING = "synthesizing"
    COMPLETE = "complete"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TaskStatus(str, Enum):
    """Status of an individual research task."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETE = "complete"
    FAILED = "failed"
    SKIPPED = "skipped"


class SourceType(str, Enum):
    """The type/origin of a source."""

    WEB_PAGE = "web_page"
    PDF = "pdf"
    NEWS = "news"
    ACADEMIC = "academic"
    VIDEO_TRANSCRIPT = "video_transcript"
    UNKNOWN = "unknown"


class ConfidenceLevel(str, Enum):
    """Human-readable confidence tier."""

    VERY_LOW = "very_low"    # < 0.2
    LOW = "low"              # 0.2 – 0.4
    MEDIUM = "medium"        # 0.4 – 0.6
    HIGH = "high"            # 0.6 – 0.8
    VERY_HIGH = "very_high"  # > 0.8


class OutputFormat(str, Enum):
    """Desired output format for the final report."""

    MARKDOWN = "markdown"
    JSON = "json"


# ---------------------------------------------------------------------------
# Supporting Models
# ---------------------------------------------------------------------------


class Source(BaseModel):
    """A single information source discovered during research."""

    source_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    url: str
    title: str
    snippet: str = ""
    source_type: SourceType = SourceType.UNKNOWN
    domain: str = ""
    published_at: datetime | None = None
    fetched_at: datetime = Field(default_factory=datetime.utcnow)
    credibility_score: float = Field(default=0.5, ge=0.0, le=1.0)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("credibility_score")
    @classmethod
    def clamp_credibility(cls, v: float) -> float:
        return max(0.0, min(1.0, v))


class Finding(BaseModel):
    """A piece of information extracted from one or more sources."""

    finding_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    content: str
    summary: str = ""
    sources: list[Source] = Field(default_factory=list)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    tags: list[str] = Field(default_factory=list)
    contradicts: list[str] = Field(
        default_factory=list,
        description="finding_ids this finding contradicts",
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def confidence_level(self) -> ConfidenceLevel:
        if self.confidence < 0.2:
            return ConfidenceLevel.VERY_LOW
        elif self.confidence < 0.4:
            return ConfidenceLevel.LOW
        elif self.confidence < 0.6:
            return ConfidenceLevel.MEDIUM
        elif self.confidence < 0.8:
            return ConfidenceLevel.HIGH
        return ConfidenceLevel.VERY_HIGH


class ResearchGap(BaseModel):
    """A gap or missing piece of evidence identified by the Critic."""

    gap_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    description: str
    related_task_ids: list[str] = Field(default_factory=list)
    severity: str = Field(
        default="medium",
        description="low | medium | high",
    )
    suggested_query: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Contradiction(BaseModel):
    """A detected contradiction between two findings."""

    contradiction_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    finding_id_a: str
    finding_id_b: str
    description: str
    resolution: str = ""   # how the synthesizer should handle it


# ---------------------------------------------------------------------------
# Planning Models
# ---------------------------------------------------------------------------


class ResearchTask(BaseModel):
    """A single atomic research task generated by the Planner."""

    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    parent_run_id: str
    query: str
    rationale: str = ""
    priority: int = Field(default=5, ge=1, le=10)
    status: TaskStatus = TaskStatus.PENDING
    max_sources: int = 5
    findings: list[Finding] = Field(default_factory=list)
    error: str | None = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class ResearchPlan(BaseModel):
    """The Planner's output: a set of tasks to research."""

    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    run_id: str
    original_query: str
    tasks: list[ResearchTask] = Field(default_factory=list)
    estimated_depth: ResearchDepth = ResearchDepth.STANDARD
    rationale: str = ""
    created_at: datetime = Field(default_factory=datetime.utcnow)

    @property
    def total_tasks(self) -> int:
        return len(self.tasks)

    @property
    def completed_tasks(self) -> int:
        return sum(1 for t in self.tasks if t.status == TaskStatus.COMPLETE)

    @property
    def progress(self) -> float:
        if not self.tasks:
            return 0.0
        return self.completed_tasks / self.total_tasks


# ---------------------------------------------------------------------------
# Critic Models
# ---------------------------------------------------------------------------


class Critique(BaseModel):
    """The Critic's evaluation of the current research state."""

    critique_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    run_id: str
    pass_number: int = 1
    gaps: list[ResearchGap] = Field(default_factory=list)
    contradictions: list[Contradiction] = Field(default_factory=list)
    weak_sources: list[str] = Field(
        default_factory=list,
        description="source_ids flagged as low credibility",
    )
    overall_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    sufficient: bool = False
    reasoning: str = ""
    suggested_follow_up_queries: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Report Models
# ---------------------------------------------------------------------------


class ReportSection(BaseModel):
    """A single section of the final report."""

    title: str
    content: str
    supporting_finding_ids: list[str] = Field(default_factory=list)


class Citation(BaseModel):
    """A formatted citation in the final report."""

    citation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    source: Source
    referenced_in: list[str] = Field(
        default_factory=list,
        description="section titles that reference this citation",
    )


class TokenUsage(BaseModel):
    """Tracks LLM token consumption for cost accounting."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    estimated_cost_usd: float = 0.0


class FinalReport(BaseModel):
    """The Synthesizer's final structured research report."""

    report_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    run_id: str
    query: str
    executive_summary: str
    sections: list[ReportSection] = Field(default_factory=list)
    citations: list[Citation] = Field(default_factory=list)
    overall_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    confidence_level: ConfidenceLevel = ConfidenceLevel.MEDIUM
    gaps_acknowledged: list[ResearchGap] = Field(default_factory=list)
    contradictions_noted: list[Contradiction] = Field(default_factory=list)
    total_sources: int = 0
    total_findings: int = 0
    critic_passes: int = 0
    token_usage: TokenUsage = Field(default_factory=TokenUsage)
    output_format: OutputFormat = OutputFormat.MARKDOWN
    created_at: datetime = Field(default_factory=datetime.utcnow)
    elapsed_seconds: float = 0.0

    def model_post_init(self, __context: Any) -> None:
        """Derive confidence level from score after init."""
        score = self.overall_confidence
        if score < 0.2:
            self.confidence_level = ConfidenceLevel.VERY_LOW
        elif score < 0.4:
            self.confidence_level = ConfidenceLevel.LOW
        elif score < 0.6:
            self.confidence_level = ConfidenceLevel.MEDIUM
        elif score < 0.8:
            self.confidence_level = ConfidenceLevel.HIGH
        else:
            self.confidence_level = ConfidenceLevel.VERY_HIGH


# ---------------------------------------------------------------------------
# Request Model
# ---------------------------------------------------------------------------


class ResearchRequest(BaseModel):
    """The top-level input to the research agent."""

    run_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    query: str = Field(..., min_length=10, max_length=2000)
    depth: ResearchDepth = ResearchDepth.STANDARD
    max_sources: int = Field(default=10, ge=1, le=50)
    focus_domains: list[str] = Field(
        default_factory=list,
        description="Optional domains to focus search on (e.g. arxiv.org)",
    )
    output_format: OutputFormat = OutputFormat.MARKDOWN
    created_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @property
    def depth_config(self) -> dict[str, int]:
        """Return depth-specific limits."""
        configs = {
            ResearchDepth.QUICK:    {"max_tasks": 3, "max_critic_passes": 1, "max_sources": min(self.max_sources, 5)},
            ResearchDepth.STANDARD: {"max_tasks": 6, "max_critic_passes": 2, "max_sources": min(self.max_sources, 12)},
            ResearchDepth.DEEP:     {"max_tasks": 12, "max_critic_passes": 3, "max_sources": min(self.max_sources, 25)},
        }
        return configs[self.depth]
