"""
app/harness/context.py
======================
The execution context tracking runtime configurations, metrics, and guards for a single run.
"""

from datetime import datetime
from typing import Any

from app.domain import ExecutionMetrics, RunMetadata, TokenUsage
from app.harness.budget import BudgetGuard
from app.harness.cancellation import CancellationToken
from app.harness.exceptions import TimeoutError
from app.harness.policies import PolicyEvaluator
from app.utils.time import is_expired, utcnow


class RunContext:
    """Combines execution identities, limits, timing, and security evaluations for a run."""

    def __init__(
        self,
        run_id: str,
        thread_id: str,
        budget_guard: BudgetGuard,
        policy_evaluator: PolicyEvaluator,
        cancellation_token: CancellationToken,
        session_id: str | None = None,
        user_id: str | None = None,
        started_at: datetime | None = None,
        deadline: datetime | None = None,
    ) -> None:
        self.run_id = run_id
        self.thread_id = thread_id
        self.session_id = session_id
        self.user_id = user_id

        self.started_at = started_at or utcnow()
        self.deadline = deadline

        self.budget_guard = budget_guard
        self.policy_evaluator = policy_evaluator
        self.cancellation_token = cancellation_token

        # Accumulator for real-time execution resource metrics
        self.metrics = ExecutionMetrics()

    def raise_if_cancelled(self) -> None:
        """Raises CancellationError if cancellation is signaled."""
        self.cancellation_token.raise_if_cancelled()

    def raise_if_timed_out(self) -> None:
        """Raises TimeoutError if the current execution time has exceeded the deadline."""
        if self.deadline and is_expired(self.deadline):
            raise TimeoutError(
                message=f"Run timed out: execution exceeded target deadline of {self.deadline.isoformat()}.",
                run_id=self.run_id,
            )

    def raise_if_budget_exhausted(self) -> None:
        """Raises BudgetExhaustedError if any budget resource constraint has been breached."""
        self.budget_guard.check_all(self.metrics, self.started_at)

    def verify_guards(self) -> None:
        """Helper to run all guards (cancellation, timeout, budget) in a single invocation."""
        self.raise_if_cancelled()
        self.raise_if_timed_out()
        self.raise_if_budget_exhausted()

    def record_llm_call(self, prompt_tokens: int, completion_tokens: int, cost: float) -> None:
        """
        Updates internal metrics with LLM call token consumption.

        Args:
            prompt_tokens: Input tokens used in the prompt.
            completion_tokens: Output tokens generated by the model.
            cost: Estimated cost of the call in USD.
        """
        # Increment prompt/completion token usage
        added_usage = TokenUsage(
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
            total_tokens=prompt_tokens + completion_tokens,
            estimated_cost_usd=cost,
        )
        self.metrics.token_usage = self.metrics.token_usage + added_usage
        self.metrics.total_llm_calls += 1

        # Proactively check budget after update
        self.raise_if_budget_exhausted()

    def record_tool_call(self) -> None:
        """Updates internal metrics following a tool execution."""
        self.metrics.total_tool_calls += 1

        # Proactively check budget after update
        self.raise_if_budget_exhausted()

    def to_metadata(self, model_name: str) -> RunMetadata:
        """
        Converts the runtime context into a serializable RunMetadata domain model
        for injection into the graph's shared state.
        """
        return RunMetadata(
            run_id=self.run_id,
            thread_id=self.thread_id,
            session_id=self.session_id,
            user_id=self.user_id,
            started_at=self.started_at,
            deadline=self.deadline,
            model_name=model_name,
            max_critic_passes=self.budget_guard.budget.max_iterations,
            max_tasks=self.budget_guard.budget.max_llm_calls,  # Using standard task count config
            max_sources_per_task=self.budget_guard.budget.max_tool_calls,
            token_budget=self.budget_guard.budget.max_input_tokens,
            cost_budget_usd=self.budget_guard.budget.max_cost_usd,
            timeout_seconds=self.budget_guard.budget.max_duration_seconds,
            retry_count=0,
        )
